import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Drawer from "./components/Drawer";
import GlobalsProvider from "./contexts/Globals";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icon: "/favicon.ico",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalsProvider>
          <div className="overflow-hidden">
            <NavBar />
            <Drawer />
            <Toaster />
            <Sonner />
            {children}
          </div>
        </GlobalsProvider>
      </body>
    </html>
  );
}
